repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: 
  - id: black
    exclude: docs/scripts/how_splitting_works.py
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
  - id: ruff
    args: ["--fix", "--exit-non-zero-on-fix"]
- repo: local
  hooks:
  - id: pytest
    name: pytest (uv)
    entry: uv run pytest --maxfail=1 -q
    language: system
    pass_filenames: false 
