name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.4.0

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release  # Use GitHub environment for additional protection
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Verify tag matches version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        PACKAGE_VERSION=$(python -c "import sys; sys.path.insert(0, 'src'); from attachments import __version__; print(__version__)")
        echo "Tag version: $TAG_VERSION"
        echo "Package version: $PACKAGE_VERSION"
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "Version mismatch between tag and package!"
          exit 1
        fi

    - name: Clean dist directory
      run: rm -rf dist/

    - name: Build package
      run: python -m build

    - name: Verify package
      run: |
        twine check dist/*
        ls -la dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Use trusted publishing instead of API tokens
        # Configure this in your PyPI account settings
        attestations: true
        print-hash: true 